version: "3.7"

services:
  app:
    image: alpomoney-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - dev-database
    environment:
      - DATABASE_URL=postgres://alpomoney:alpomoney@dev-database:5432/alpomoney
  dev-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alpomoney
      POSTGRES_PASSWORD: alpomoney
      POSTGRES_DB: alpomoney
  # test-database:
  #   image: postgres
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: alpomoney
  #     POSTGRES_PASSWORD: alpomoney
  #     POSTGRES_DB: alpomoney-test
