name: Run tests
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alpomoney
          POSTGRES_PASSWORD: alpomoney
          POSTGRES_DB: alpomoney-test        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgres://alpomoney:alpomoney@postgres:5432/alpomoney-test
          
      - name: Connect to PostgreSQL
        run: npm test:github
        env:
          DATABASE_URL: postgres://alpomoney:alpomoney@postgres:5432/alpomoney-test